export const books = [
    {
      "author": "Chinua Achebe",
      "country": "Nigeria",
      "image": require("./images/books/things-fall-apart.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
      "pages": 209,
      "title": "Things Fall Apart",
      "year": 1958,
      "price": 250,
      "id": "1"
    },
    {
      "author": "Hans Christian Andersen",
      "country": "Denmark",
      "image": require("./images/books/fairy-tales.jpg"),
      "language": "Danish",
      "link": "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
      "pages": 784,
      "title": "Fairy tales",
      "year": 1836,
      "price": 250,
      "id": "2"
    },
    {
      "author": "Dante Alighieri",
      "country": "Italy",
      "image": require("./images/books/the-divine-comedy.jpg"),
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/Divine_Comedy\n",
      "pages": 928,
      "title": "The Divine Comedy",
      "year": 1315,
      "price": 250,
      "id": "3"
    },
    {
      "author": "Maureen Kovacs",
      "country": "Sumer and Akkadian Empire",
      "image": require("./images/books/the-epic-of-gilgamesh.jpg"),
      "language": "Akkadian",
      "link": "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
      "pages": 160,
      "title": "The Epic Of Gilgamesh",
      "year": -1700,
      "price": 250,
      "id": "4"
    },
    {
      "author": "Stephen Mitchell",
      "country": "Achaemenid Empire",
      "image": require("./images/books/the-book-of-job.jpg"),
      "language": "Hebrew",
      "link": "https://en.wikipedia.org/wiki/Book_of_Job\n",
      "pages": 176,
      "title": "The Book Of Job",
      "year": -600,
      "price": 250,
      "id": "5"
    },
    {
      "author": "Geraldine McCaughrean",
      "country": "India/Iran/Iraq/Egypt/Tajikistan",
      "image": require("./images/books/one-thousand-and-one-nights.jpg"),
      "language": "Arabic",
      "link": "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
      "pages": 288,
      "title": "One Thousand and One Nights",
      "year": 1200,
      "price": 250,
      "id": "6"
    },
    {
      "author": "Robert Cook",
      "country": "Iceland",
      "image": require("./images/books/njals-saga.jpg"),
      "language": "Old Norse",
      "link": "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
      "pages": 384,
      "title": "Nj\u00e1l's Saga",
      "year": 1350,
      "price": 250,
      "id": "7"
    },
    {
      "author": "Jane Austen",
      "country": "United Kingdom",
      "image": require("./images/books/pride-and-prejudice.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
      "pages": 226,
      "title": "Pride and Prejudice",
      "year": 1813,
      "price": 250,
      "id": "8"
    },
    {
      "author": "Honor\u00e9 de Balzac",
      "country": "France",
      "image": require("./images/books/le-pere-goriot.jpg"),
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
      "pages": 443,
      "title": "Le P\u00e8re Goriot",
      "year": 1835,
      "price": 250,
      "id": "9"
    },
    {
      "author": "Samuel Beckett",
      "country": "Republic of Ireland",
      "image": require("./images/books/molloy-malone-dies-the-unnamable.jpg"),
      "language": "French, English",
      "link": "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
      "pages": 256,
      "title": "Molloy, Malone Dies, The Unnamable, the trilogy",
      "year": 1952,
      "price": 250,
      "id": "10"
    },
    {
      "author": "Giovanni Boccaccio",
      "country": "Italy",
      "image": require("./images/books/the-decameron.jpg"),
      "language": "Italian",
      "link": "https://en.wikipedia.org/wiki/The_Decameron\n",
      "pages": 1024,
      "title": "The Decameron",
      "year": 1351,
      "price": 250,
      "id": "11"
    },
    {
      "author": "Jorge Luis Borges",
      "country": "Argentina",
      "image": require("./images/books/ficciones.jpg"),
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Ficciones\n",
      "pages": 224,
      "title": "Ficciones",
      "year": 1965,
      "price": 250,
      "id": "12"
    },
    {
      "author": "Emily Bront\u00eb",
      "country": "United Kingdom",
      "image": require("./images/books/wuthering-heights.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
      "pages": 342,
      "title": "Wuthering Heights",
      "year": 1847,
      "price": 250,
      "id": "13"
    },
    {
      "author": "Albert Camus",
      "country": "Algeria, French Empire",
      "image": require("./images/books/l-etranger.jpg"),
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
      "pages": 185,
      "title": "The Stranger",
      "year": 1942,
      "price": 250,
      "id": "14"
    },
    {
      "author": "Paul Celan",
      "country": "Romania, France",
      "image": require("./images/books/poems-paul-celan.jpg"),
      "language": "German",
      "link": "\n",
      "pages": 320,
      "title": "Poems",
      "year": 1952,
      "price": 250,
      "id": "15"
    },
    {
      "author": "Louis-Ferdinand C\u00e9line",
      "country": "France",
      "image": require("./images/books/voyage-au-bout-de-la-nuit.jpg"),
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
      "pages": 505,
      "title": "Journey to the End of the Night",
      "year": 1932,
      "price": 250,
      "id": "16"
    },
    {
      "author": "Miguel de Cervantes",
      "country": "Spain",
      "image": require("./images/books/don-quijote-de-la-mancha.jpg"),
      "language": "Spanish",
      "link": "https://en.wikipedia.org/wiki/Don_Quixote\n",
      "pages": 1056,
      "title": "Don Quijote De La Mancha",
      "year": 1610,
      "price": 250,
      "id": "17"
    },
    {
      "author": "Geoffrey Chaucer",
      "country": "England",
      "image": require("./images/books/the-canterbury-tales.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
      "pages": 544,
      "title": "The Canterbury Tales",
      "year": 1450,
      "price": 250,
      "id": "18"
    },
    {
      "author": "Anton Chekhov",
      "country": "Russia",
      "image": require("./images/books/stories-of-anton-chekhov.jpg"),
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
      "pages": 194,
      "title": "Stories",
      "year": 1886,
      "price": 250,
      "id": "19"
    },
    {
      "author": "Joseph Conrad",
      "country": "United Kingdom",
      "image": require("./images/books/nostromo.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Nostromo\n",
      "pages": 320,
      "title": "Nostromo",
      "year": 1904,
      "price": 250,
      "id": "20"
    },
    {
      "author": "Charles Dickens",
      "country": "United Kingdom",
      "image": require("./images/books/great-expectations.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Great_Expectations\n",
      "pages": 194,
      "title": "Great Expectations",
      "year": 1861,
      "price": 250,
      "id": "21"
    },
    {
      "author": "Denis Diderot",
      "country": "France",
      "image": require("./images/books/jacques-the-fatalist.jpg"),
      "language": "French",
      "link": "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
      "pages": 596,
      "title": "Jacques the Fatalist",
      "year": 1796,
      "price": 250,
      "id": "22"
    },
    {
      "author": "Alfred D\u00f6blin",
      "country": "Germany",
      "image": require("./images/books/berlin-alexanderplatz.jpg"),
      "language": "German",
      "link": "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
      "pages": 600,
      "title": "Berlin Alexanderplatz",
      "year": 1929,
      "price": 250,
      "id": "23"
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "image": require("./images/books/crime-and-punishment.jpg"),
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
      "pages": 551,
      "title": "Crime and Punishment",
      "year": 1866,
      "price": 250,
      "id": "24"
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "image": require("./images/books/the-idiot.jpg"),
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Idiot\n",
      "pages": 656,
      "title": "The Idiot",
      "year": 1869,
      "price": 250,
      "id": "25"
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "image": require("./images/books/the-possessed.jpg"),
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
      "pages": 768,
      "title": "The Possessed",
      "year": 1872,
      "price": 250,
      "id": "26"
    },
    {
      "author": "Fyodor Dostoevsky",
      "country": "Russia",
      "image": require("./images/books/the-brothers-karamazov.jpg"),
      "language": "Russian",
      "link": "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
      "pages": 824,
      "title": "The Brothers Karamazov",
      "year": 1880,
      "price": 250,
      "id": "27"
    },
    {
      "author": "George Eliot",
      "country": "United Kingdom",
      "image": require("./images/books/middlemarch.jpg"),
      "language": "English",
      "link": "https://en.wikipedia.org/wiki/Middlemarch\n",
      "pages": 800,
      "title": "Middlemarch",
      "year": 1871,
      "price": 250,
      "id": "28"
    },
  ]